import type { Module } from './types';

const module: Module = {
  id: 'module6',
  slug: 'futur-simple',
  title: 'Le Futur Simple',
  subtitle: 'The simple future tense for more distant or formal events',
  color: 'bg-indigo-600',
  icon: '🔮',
  reference: [
    {
      title: 'Formation',
      body: 'For regular verbs: take the infinitive (drop the final -e for -RE verbs) and add the future endings. Irregular verbs use special stems but the same endings.',
      tables: [
        {
          title: 'Future Endings (add to infinitive/stem)',
          headers: ['Person', 'Ending'],
          rows: [
            { label: 'je', cells: ['-ai'] },
            { label: 'tu', cells: ['-as'] },
            { label: 'il / elle / on', cells: ['-a'] },
            { label: 'nous', cells: ['-ons'] },
            { label: 'vous', cells: ['-ez'] },
            { label: 'ils / elles', cells: ['-ont'] },
          ],
          note: 'For -RE verbs, drop the final -e before adding endings (vendre → vendr- + ai = vendrai).',
        },
        {
          title: 'Irregular Stems',
          headers: ['Infinitive', 'Stem'],
          rows: [
            { label: 'être', cells: ['ser-'] },
            { label: 'avoir', cells: ['aur-'] },
            { label: 'aller', cells: ['ir-'] },
            { label: 'faire', cells: ['fer-'] },
            { label: 'pouvoir', cells: ['pourr-'] },
            { label: 'voir', cells: ['verr-'] },
            { label: 'devoir', cells: ['devr-'] },
            { label: 'venir', cells: ['viendr-'] },
            { label: 'vouloir', cells: ['voudr-'] },
          ],
        },
      ],
    },
  ],
  exercises: [
    {
      type: 'fill-blank',
      id: 'm6-e1',
      sentence: 'Tu ___ les devoirs demain.',
      blanks: [['feras']],
      hint: 'faire (tu) — irregular stem fer-',
      explanation: 'faire → stem fer- + as = feras.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e2',
      sentence: 'Nous ___ en voyage.',
      blanks: [['partirons']],
      hint: 'partir (nous)',
      explanation: 'partir → infinitive stem partir- + ons = partirons.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e3',
      sentence: 'Je ___ mes amis ce soir.',
      blanks: [['verrai']],
      hint: 'voir (je) — irregular stem verr-',
      explanation: 'voir → stem verr- + ai = verrai.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e4',
      sentence: 'Ils ___ venir demain.',
      blanks: [['pourront']],
      hint: 'pouvoir (ils) — irregular stem pourr-',
      explanation: 'pouvoir → stem pourr- + ont = pourront.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e5',
      sentence: 'Marie ___ à la conférence.',
      blanks: [['parlera']],
      hint: 'parler (elle)',
      explanation: 'parler → infinitive + a = parlera.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e6',
      sentence: 'Tu ___ docteur un jour.',
      blanks: [['seras']],
      hint: 'être (tu) — irregular stem ser-',
      explanation: 'être → stem ser- + as = seras.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e7',
      sentence: 'Vous ___ à Paris.',
      blanks: [['irez']],
      hint: 'aller (vous) — irregular stem ir-',
      explanation: 'aller → stem ir- + ez = irez.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e8',
      sentence: 'Je ___ ma maison.',
      blanks: [['vendrai']],
      hint: 'vendre (je) — drop -e from stem',
      explanation: 'vendre → stem vendr- + ai = vendrai.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e9',
      sentence: 'Marie et Jean ___ de la chance.',
      blanks: [['auront']],
      hint: 'avoir (ils) — irregular stem aur-',
      explanation: 'avoir → stem aur- + ont = auront.',
    },
    {
      type: 'fill-blank',
      id: 'm6-e10',
      sentence: 'Il ___ partir tôt.',
      blanks: [['devra']],
      hint: 'devoir (il) — irregular stem devr-',
      explanation: 'devoir → stem devr- + a = devra.',
    },
    {
      type: 'translate',
      id: 'm6-t1',
      prompt: 'I will be (futur simple)',
      accepted: ['je serai'],
      explanation: 'être → ser- + ai = serai.',
    },
    {
      type: 'translate',
      id: 'm6-t2',
      prompt: 'She will eat (futur simple)',
      accepted: ['elle mangera'],
      explanation: 'manger → infinitive + a = mangera.',
    },
    {
      type: 'translate',
      id: 'm6-t3',
      prompt: 'We will go (futur simple)',
      accepted: ['nous irons'],
      explanation: 'aller → stem ir- + ons = irons.',
    },
    {
      type: 'translate',
      id: 'm6-t4',
      prompt: 'You will finish (futur simple, tu)',
      accepted: ['tu finiras'],
      explanation: 'finir → infinitive + as = finiras.',
    },
    {
      type: 'translate',
      id: 'm6-t5',
      prompt: 'They (masc.) will sell (futur simple)',
      accepted: ['ils vendront'],
      explanation: 'vendre → stem vendr- + ont = vendront.',
    },
  ],
};

export default module;
