import type { Module } from './types';

const module: Module = {
  id: 'module1',
  slug: 'present',
  title: 'Le Présent',
  subtitle: 'Present tense conjugation for regular and irregular verbs',
  color: 'bg-blue-600',
  icon: '🕐',
  reference: [
    {
      title: 'Regular Verb Endings',
      tables: [
        {
          title: '-ER verbs (e.g. parler)',
          headers: ['Person', 'Ending', 'Example'],
          rows: [
            { label: 'je', cells: ['-e', 'parle'] },
            { label: 'tu', cells: ['-es', 'parles'] },
            { label: 'il / elle / on', cells: ['-e', 'parle'] },
            { label: 'nous', cells: ['-ons', 'parlons'] },
            { label: 'vous', cells: ['-ez', 'parlez'] },
            { label: 'ils / elles', cells: ['-ent', 'parlent'] },
          ],
        },
        {
          title: '-IR verbs (e.g. choisir)',
          headers: ['Person', 'Ending', 'Example'],
          rows: [
            { label: 'je', cells: ['-is', 'choisis'] },
            { label: 'tu', cells: ['-is', 'choisis'] },
            { label: 'il / elle / on', cells: ['-it', 'choisit'] },
            { label: 'nous', cells: ['-issons', 'choisissons'] },
            { label: 'vous', cells: ['-issez', 'choisissez'] },
            { label: 'ils / elles', cells: ['-issent', 'choisissent'] },
          ],
        },
        {
          title: '-RE verbs (e.g. vendre)',
          headers: ['Person', 'Ending', 'Example'],
          rows: [
            { label: 'je', cells: ['-s', 'vends'] },
            { label: 'tu', cells: ['-s', 'vends'] },
            { label: 'il / elle / on', cells: ['—', 'vend'] },
            { label: 'nous', cells: ['-ons', 'vendons'] },
            { label: 'vous', cells: ['-ez', 'vendez'] },
            { label: 'ils / elles', cells: ['-ent', 'vendent'] },
          ],
        },
      ],
    },
    {
      title: 'Irregular Verbs',
      tables: [
        {
          title: 'avoir (to have)',
          headers: ['Person', 'Form'],
          rows: [
            { label: 'je', cells: ['ai'] },
            { label: 'tu', cells: ['as'] },
            { label: 'il / elle / on', cells: ['a'] },
            { label: 'nous', cells: ['avons'] },
            { label: 'vous', cells: ['avez'] },
            { label: 'ils / elles', cells: ['ont'] },
          ],
        },
        {
          title: 'être (to be)',
          headers: ['Person', 'Form'],
          rows: [
            { label: 'je', cells: ['suis'] },
            { label: 'tu', cells: ['es'] },
            { label: 'il / elle / on', cells: ['est'] },
            { label: 'nous', cells: ['sommes'] },
            { label: 'vous', cells: ['êtes'] },
            { label: 'ils / elles', cells: ['sont'] },
          ],
        },
        {
          title: 'faire (to do / make)',
          headers: ['Person', 'Form'],
          rows: [
            { label: 'je', cells: ['fais'] },
            { label: 'tu', cells: ['fais'] },
            { label: 'il / elle / on', cells: ['fait'] },
            { label: 'nous', cells: ['faisons'] },
            { label: 'vous', cells: ['faites'] },
            { label: 'ils / elles', cells: ['font'] },
          ],
        },
        {
          title: 'aller (to go)',
          headers: ['Person', 'Form'],
          rows: [
            { label: 'je', cells: ['vais'] },
            { label: 'tu', cells: ['vas'] },
            { label: 'il / elle / on', cells: ['va'] },
            { label: 'nous', cells: ['allons'] },
            { label: 'vous', cells: ['allez'] },
            { label: 'ils / elles', cells: ['vont'] },
          ],
        },
      ],
    },
  ],
  exercises: [
    {
      type: 'fill-blank',
      id: 'm1-e1',
      sentence: 'Je ___ toujours mes devoirs!',
      blanks: [['fais']],
      hint: 'faire (je)',
      explanation: 'faire → je fais (irregular; the nous/vous forms are faisons/faites/font).',
    },
    {
      type: 'fill-blank',
      id: 'm1-e2',
      sentence: 'Nous ___ à notre professeur.',
      blanks: [['parlons']],
      hint: 'parler (nous)',
      explanation: '-ER verbs take -ons for nous.',
    },
    {
      type: 'fill-blank',
      id: 'm1-e3',
      sentence: 'Elle ___ une voiture.',
      blanks: [['choisit']],
      hint: 'choisir (elle)',
      explanation: '-IR verbs take -it for il/elle/on.',
    },
    {
      type: 'fill-blank',
      id: 'm1-e4',
      sentence: 'Ils ne ___ pas fatigués!',
      blanks: [['sont']],
      hint: 'être (ils)',
      explanation: 'être → ils sont (irregular).',
    },
    {
      type: 'fill-blank',
      id: 'm1-e5',
      sentence: 'Toi et Marie ___ au cinéma.',
      blanks: [['allez']],
      hint: 'aller — toi et Marie = vous',
      explanation: 'toi et Marie = vous; aller → vous allez.',
    },
    {
      type: 'fill-blank',
      id: 'm1-e6',
      sentence: 'Le chien ___ marcher.',
      blanks: [['aime']],
      hint: 'aimer (il)',
      explanation: '-ER verbs take -e for il/elle/on.',
    },
    {
      type: 'fill-blank',
      id: 'm1-e7',
      sentence: "Je n'___ pas faim.",
      blanks: [['ai']],
      hint: 'avoir (je)',
      explanation: 'avoir → j\'ai (irregular).',
    },
    {
      type: 'fill-blank',
      id: 'm1-e8',
      sentence: 'Les enfants ___ beaucoup de bruit.',
      blanks: [['font']],
      hint: 'faire (ils)',
      explanation: 'faire → ils font (irregular).',
    },
    {
      type: 'fill-blank',
      id: 'm1-e9',
      sentence: 'Elles ___ les livres.',
      blanks: [['vendent']],
      hint: 'vendre (elles)',
      explanation: '-RE verbs take -ent for ils/elles.',
    },
    {
      type: 'fill-blank',
      id: 'm1-e10',
      sentence: 'Vous ne ___ pas la course.',
      blanks: [['finissez']],
      hint: 'finir (vous)',
      explanation: '-IR verbs take -issez for vous.',
    },
  ],
};

export default module;
