import type { Module } from './types';

const module: Module = {
  id: 'module4',
  slug: 'passe-avoir',
  title: 'Le Passé Composé (avoir)',
  subtitle: 'Past tense formed with avoir as auxiliary',
  color: 'bg-orange-600',
  icon: '📖',
  reference: [
    {
      title: 'Formation: avoir + past participle',
      body: 'The passé composé with avoir = present tense of avoir + past participle. The past participle does NOT agree with the subject (unlike être verbs).',
      tables: [
        {
          title: 'avoir (present)',
          headers: ['Person', 'Form'],
          rows: [
            { label: 'je', cells: ['ai'] },
            { label: 'tu', cells: ['as'] },
            { label: 'il / elle / on', cells: ['a'] },
            { label: 'nous', cells: ['avons'] },
            { label: 'vous', cells: ['avez'] },
            { label: 'ils / elles', cells: ['ont'] },
          ],
        },
        {
          title: 'Regular Past Participles',
          headers: ['Verb type', 'Rule', 'Example'],
          rows: [
            { label: '-ER verbs', cells: ['drop -er, add -é', 'parler → parlé'] },
            { label: '-RE verbs', cells: ['drop -re, add -u', 'vendre → vendu'] },
            { label: '-IR verbs', cells: ['drop -ir, add -i', 'finir → fini'] },
          ],
        },
        {
          title: 'Irregular Past Participles',
          headers: ['Infinitive', 'Past Participle'],
          rows: [
            { label: 'écrire', cells: ['écrit'] },
            { label: 'faire', cells: ['fait'] },
            { label: 'être', cells: ['été'] },
            { label: 'avoir', cells: ['eu'] },
            { label: 'recevoir', cells: ['reçu'] },
            { label: 'voir', cells: ['vu'] },
            { label: 'prendre', cells: ['pris'] },
            { label: 'mettre', cells: ['mis'] },
            { label: 'dire', cells: ['dit'] },
            { label: 'vouloir', cells: ['voulu'] },
            { label: 'devoir', cells: ['dû'] },
            { label: 'pouvoir', cells: ['pu'] },
            { label: 'boire', cells: ['bu'] },
            { label: 'dormir', cells: ['dormi'] },
            { label: 'mentir', cells: ['menti'] },
            { label: 'servir', cells: ['servi'] },
          ],
        },
      ],
    },
  ],
  exercises: [
    {
      type: 'fill-blank',
      id: 'm4-e1',
      sentence: 'Le garçon ___ notre repas.',
      blanks: [['a servi']],
      hint: 'servir (il) — irregular PP',
      explanation: 'servir → servi; il a servi.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e2',
      sentence: "Je n'___ pas ___ aller au cinéma.",
      blanks: [['ai'], ['pu']],
      hint: 'pouvoir (je) — two blanks: aux + PP',
      explanation: 'pouvoir → pu; je n\'ai pas pu (aux in negative goes between ne…pas).',
    },
    {
      type: 'fill-blank',
      id: 'm4-e3',
      sentence: 'Mes sœurs ___ à nos parents.',
      blanks: [['ont menti']],
      hint: 'mentir (elles)',
      explanation: 'mentir → menti; elles ont menti.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e4',
      sentence: 'Il ___ rester à la maison.',
      blanks: [['a voulu']],
      hint: 'vouloir (il)',
      explanation: 'vouloir → voulu; il a voulu.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e5',
      sentence: "Tu ___ jusqu'à midi.",
      blanks: [['as dormi']],
      hint: 'dormir (tu)',
      explanation: 'dormir → dormi; tu as dormi.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e6',
      sentence: 'Mon père ___ un café.',
      blanks: [['a bu']],
      hint: 'boire (il)',
      explanation: 'boire → bu; il a bu.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e7',
      sentence: "Mon ami ___ qu'il pourra venir.",
      blanks: [['a dit']],
      hint: 'dire (il)',
      explanation: 'dire → dit; il a dit.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e8',
      sentence: 'Vous ___ le 25 décembre.',
      blanks: [['avez travaillé']],
      hint: 'travailler (vous)',
      explanation: 'travailler → travaillé (regular -ER); vous avez travaillé.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e9',
      sentence: "J'___ un grand manteau.",
      blanks: [['ai mis']],
      hint: 'mettre (je)',
      explanation: 'mettre → mis; j\'ai mis.',
    },
    {
      type: 'fill-blank',
      id: 'm4-e10',
      sentence: "J'___ à mon père.",
      blanks: [['ai demandé']],
      hint: 'demander (je)',
      explanation: 'demander → demandé (regular -ER); j\'ai demandé.',
    },
  ],
};

export default module;
