import type { Module } from './types';

const module: Module = {
  id: 'module5',
  slug: 'passe-etre',
  title: 'Le Passé Composé (être)',
  subtitle: 'DR MRS VANDERTRAMP verbs + agreement rules',
  color: 'bg-red-600',
  icon: '🏃',
  reference: [
    {
      title: 'Formation with être',
      body: 'Certain verbs (the DR MRS VANDERTRAMP group, plus all reflexive verbs) use être — not avoir — as their auxiliary. The past participle MUST agree with the subject in gender and number.',
      tables: [
        {
          title: 'Agreement endings',
          headers: ['', 'Singular', 'Plural'],
          rows: [
            { label: 'Masculine', cells: ['—', '+s'] },
            { label: 'Feminine', cells: ['+e', '+es'] },
          ],
        },
        {
          title: 'DR MRS VANDERTRAMP — The 16 être verbs',
          headers: ['Infinitive', 'Past Participle', 'Meaning'],
          rows: [
            { label: 'D', cells: ['devenir / devenu', 'to become'] },
            { label: 'R', cells: ['revenir / revenu', 'to come back'] },
            { label: 'M', cells: ['monter / monté', 'to go up'] },
            { label: 'R', cells: ['rester / resté', 'to stay'] },
            { label: 'S', cells: ['sortir / sorti', 'to go out'] },
            { label: 'V', cells: ['venir / venu', 'to come'] },
            { label: 'A', cells: ['aller / allé', 'to go'] },
            { label: 'N', cells: ['naître / né', 'to be born'] },
            { label: 'D', cells: ['descendre / descendu', 'to go down'] },
            { label: 'E', cells: ['entrer / entré', 'to enter'] },
            { label: 'R', cells: ['rentrer / rentré', 'to go home'] },
            { label: 'T', cells: ['tomber / tombé', 'to fall'] },
            { label: 'R', cells: ['retourner / retourné', 'to return'] },
            { label: 'A', cells: ['arriver / arrivé', 'to arrive'] },
            { label: 'M', cells: ['mourir / mort', 'to die'] },
            { label: 'P', cells: ['partir / parti', 'to leave'] },
          ],
        },
      ],
    },
  ],
  exercises: [
    {
      type: 'fill-blank',
      id: 'm5-e1',
      sentence: 'Mes amis ___ hier.',
      blanks: [['sont arrivés']],
      hint: 'arriver (ils — masc. pl.)',
      explanation: 'arriver → arrivé + être; ils → arrivés (masc. pl., +s).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e2',
      sentence: 'Les professeurs ___ fâchés!',
      blanks: [['sont devenus']],
      hint: 'devenir (ils — masc. pl.)',
      explanation: 'devenir → devenu + être; ils → devenus (masc. pl., +s).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e3',
      sentence: "Je ___ en classe à l'heure.",
      blanks: [['suis venu', 'suis venue']],
      hint: 'venir (je) — accept masc. or fem.',
      explanation: 'venir → venu + être; je suis venu (m.) / je suis venue (f.).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e4',
      sentence: "Le loup-garou ___ quand il y a eu une pleine lune.",
      blanks: [['est sorti']],
      hint: 'sortir (il)',
      explanation: 'sortir → sorti + être; il est sorti (masc. sing., no extra ending).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e5',
      sentence: 'Nous ___ au parc.',
      blanks: [['sommes allés', 'sommes allées']],
      hint: 'aller (nous) — accept masc. or fem.',
      explanation: 'aller → allé + être; nous sommes allés (m.) / allées (f.).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e6',
      sentence: 'Marie et Claire ___ les escaliers.',
      blanks: [['sont descendues']],
      hint: 'descendre (elles — two women, fem. pl.)',
      explanation: 'descendre → descendu + être; elles → descendues (fem. pl., +es).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e7',
      sentence: 'Tu ___ dans la maison.',
      blanks: [['es entré', 'es entrée']],
      hint: 'entrer (tu) — accept masc. or fem.',
      explanation: 'entrer → entré + être; tu es entré (m.) / tu es entrée (f.).',
    },
    {
      type: 'fill-blank',
      id: 'm5-e8',
      sentence: "Vous ___ jusqu'à 14h00.",
      blanks: [['êtes restés', 'êtes restées', 'êtes resté', 'êtes restée']],
      hint: 'rester (vous) — accept all agreement forms',
      explanation: 'rester → resté + être; vous form depends on who is referred to.',
    },
    {
      type: 'fill-blank',
      id: 'm5-e9',
      sentence: 'Luc et Pauline ___ à minuit.',
      blanks: [['sont rentrés']],
      hint: 'rentrer (ils — mixed group = masc. pl.)',
      explanation: 'rentrer → rentré + être; mixed group uses masculine plural → rentrés.',
    },
    {
      type: 'fill-blank',
      id: 'm5-e10',
      sentence: 'Qui ___ ?',
      blanks: [['est tombé']],
      hint: 'tomber (qui = masc. sing. default)',
      explanation: 'tomber → tombé + être; qui defaults to masc. sing. → est tombé.',
    },
    {
      type: 'auxiliary-choice',
      id: 'm5-aux1',
      sentence: 'Il ___ venu hier soir.',
      auxAccepted: ['est'],
      ppAccepted: ['venu'],
      explanation: 'venir is a DR MRS VANDERTRAMP verb → uses être.',
    },
    {
      type: 'auxiliary-choice',
      id: 'm5-aux2',
      sentence: 'Nous ___ regardé la télé.',
      auxAccepted: ['avons'],
      ppAccepted: ['regardé'],
      explanation: 'regarder is not a DR MRS VANDERTRAMP verb → uses avoir.',
    },
    {
      type: 'auxiliary-choice',
      id: 'm5-aux3',
      sentence: 'Ils ___ vécu trois ans à Marseille.',
      auxAccepted: ['ont'],
      ppAccepted: ['vécu'],
      explanation: 'vivre uses avoir; vivre → vécu.',
    },
    {
      type: 'auxiliary-choice',
      id: 'm5-aux4',
      sentence: 'Quand je ___ sorti ce matin...',
      auxAccepted: ['suis'],
      ppAccepted: ['sorti'],
      explanation: 'sortir is a DR MRS VANDERTRAMP verb → uses être.',
    },
    {
      type: 'auxiliary-choice',
      id: 'm5-aux5',
      sentence: 'Ils ___ reçu une lettre de Luc.',
      auxAccepted: ['ont'],
      ppAccepted: ['reçu'],
      explanation: 'recevoir uses avoir; recevoir → reçu.',
    },
  ],
};

export default module;
